# Generated by Django 3.2.5 on 2021-12-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dados_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_a', models.CharField(max_length=20)),
                ('nascimento_a', models.DateField()),
                ('email_a', models.EmailField(max_length=254)),
                ('senha_a', models.CharField(max_length=15)),
            ],
        ),
    ]
