# Generated by Django 3.2.5 on 2021-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_fotog'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendencia_a', models.CharField(max_length=50)),
                ('inicio_a', models.DateTimeField(auto_now=False, auto_now_add=False)),
                ('fim_a', models.DateTimeField(auto_now=False, auto_now_add=False)),
            ],
        ),
        migrations.DeleteModel(
            name='fotog',
        ),
    ]
